### ISSUE TITLE
Version 0.0.7 intall error

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/ckanext-datapackage-creator#8]
Install error:

```
Traceback (most recent call last):
  File "/srv/app/wsgi.py", line 20, in <module>
    application = make_app(config)
  File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 27, in make_app
    load_environment(conf)
  File "/srv/app/src/ckan/ckan/config/environment.py", line 69, in load_environment
    p.load_all()
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 224, in load_all
    load(*plugins)
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 240, in load
    service = _get_service(plugin)
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 347, in _get_service
    return plugin.load()(name=plugin_name)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pkgutil-resolve-name>=1.3.10; python_version < "3.9"' distribution was not found and is required by jsonschema
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
```

[Related issue](https://github.com/transparencia-mg/work-stefanini/issues/95#issuecomment-1363333431)

**Comment by gileno** [comment]
@gabrielbdornas eu tive este problema agora pela manhã refazendo o ambiente, fui instalando cada dependência que indicava pendência até voltar ao problema do dataclasses, mas encontrei uma possível explicação:

[Indicação da remoção do dataclasses como dependência - 10/10/2022](https://github.com/Textualize/rich/blob/234d1eaa2a430c7a5766890e3bec13befca6dbc4/poetry.lockl)

![Última versão lançada da biblioteca rich 02/10/2022](https://user-images.githubusercontent.com/223948/209652042-7485efaf-cc2e-432c-8cd6-29cf5ed345f3.png)

A tag 12.6.0 que é justamente da última versão instalada da rich contém essa dependência da dataclasses:

![Arquivo do poetry.lock](https://user-images.githubusercontent.com/223948/209652434-6e39702b-0e8a-45aa-9545-31b2975dce44.png)
